version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/indiepiniata
    environment:
      - SECRET=KL08X8LS5C44KepRezOBh5dVaUFHeSnzmTNZoCRlmLll8oViVbInwVHjQ9anC2h4HL+8i1pMNpCRT2Hgtt5wGLucfYul8bSqBtvX6zemUGZKn0WBcffwZx6E0dzTtAdJaukEjXY0/Wy+5r0GIx0gMuYG+Z14lhJ5
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
